fix(compiler): should show errors for missing semicolons or braces (#1269)
Fixes #1266

After making the fix work, I discovered there were many syntax errors in our valid examples, so I fixed all of them as well.

I also noticed this sequence of commands were failing on a fresh repo:

```
npm i
cd libs/wingc
npx nx run build-native
npx nx run test
...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Expected to find .jsii file in ../wingsdk, but no such file found"', libs/wingc/src/type_check.rs:1729:18
```

The same issue applies with `npx nx run dev`.

To fix this I've added the sdk as a dependency of `wingc:dev` and `wingc:test`.

*By submitting this pull request, I confirm that my contribution is made under the terms of the 
[Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.