fix: error running wingcli-v2 tests locally (#6689)
@hasanaburayyan reported an issue running the wingcli-v2 tests locally:

```
running 2 tests
 Installing Wing SDK
test test::test_compile_sim ... FAILED
test test::test_compile_tfaws ... FAILED

failures:

---- test::test_compile_sim stdout ----
thread 'test::test_compile_sim' panicked at apps/wingcli-v2/src/main.rs:208:27:
Failed to install SDK: "Failed to install SDK. stdout: . stderr: npm ERR! code EUNSUPPORTEDPROTOCOL\nnpm ERR! Unsupported URL Type \"workspace:\": workspace:^\n\nnpm ERR! A complete log of this run can be found in: /Users/hasan/.npm/_logs/2024-06-12T16_06_47_837Z-debug-0.log\n"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test::test_compile_tfaws stdout ----
thread 'test::test_compile_tfaws' panicked at apps/wingcli-v2/src/main.rs:207:14:
Once instance has previously been poisoned
```

After a few hours we weren't able to diagnose the root cause. But as a workaround, we can avoid the issue by adding the locally built SDK to the NODE_PATH instead of using `npm install` to link the locally built SDK to the cache directory.

## Checklist

- [ ] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
- [ ] Description explains motivation and solution
- [ ] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.