chore(cli): improve error output (#6406)
Currently when you get compile errors in the CLI (related to parsing or type checking), the error message appears twice:

```
error: Enum "SomeEnum" does not contain value "FOUR"
  --> examples/tests/invalid/enums.test.w:5:21
  |
5 | let four = SomeEnum.FOUR;
  |                     ^^^^ Enum "SomeEnum" does not contain value "FOUR"
```

The repeated message can make errors look longer and doesn't add any information, so this PR removes the second occurrence of the error message.

## Checklist

- [x] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
- [x] Description explains motivation and solution
- [x] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.