fix(console): tests errors are not shown in the console (#5333)
extracting TestRunnerClient TestResult error and adding to the console logger.
for example, the following TestResult error:
```
{
  path: 'root/env0/test:hello',
  pass: false,
  error: 'AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:\n' +
    '\n' +
    '1 !== 2\n' +
    '\n' +
    '    at Util.equal (/var/folders/dy/sygfk8k13rlgxfgj6r3zkr1c0000gn/T/wing-bundles-6TowaX/index.js:7070:26)\n' +
    '    at $Closure1.handle (/var/folders/dy/sygfk8k13rlgxfgj6r3zkr1c0000gn/T/wing-bundles-6TowaX/index.js:24:30)\n' +
    '    at exports.handler (/var/folders/dy/sygfk8k13rlgxfgj6r3zkr1c0000gn/T/wing-bundles-6TowaX/index.js:7120:9)',
  traces: [
    {
      data: [Object],
      type: 'resource',
      sourcePath: 'root/env0/test:hello/Handler',
      sourceType: '@winglang/sdk.cloud.Function',
      timestamp: '2023-12-25T17:33:34.191Z'
    }
  ]
}
```
now looks like this in the console logs panel:
![Screenshot 2023-12-25 at 21 47 46](https://github.com/winglang/wing/assets/2538825/5da04544-7e1c-4f74-90a5-2c72182f733c)


resolves: https://github.com/winglang/wing/issues/5331
also resolves: https://github.com/winglang/wing/issues/4803

test output is now:
![Screenshot 2023-12-25 at 21 48 00](https://github.com/winglang/wing/assets/2538825/45de313b-6a2c-4d96-963e-371871b5c385)


## Checklist

- [ ] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
- [ ] Description explains motivation and solution
- [ ] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.