feat(compiler): compilation context in panic messages (#2734)
First step addressing issues in #1656
This currently crashes the compiler:
```wing
bring cloud;
bring util;

let shell = util.env("SHELL");
log("preflight shell ${shell}");

test "test" {
  let shell = util.env("SHELL");
  log("inflight shell ${shell}");
}
```
Now we get this to stderr (with optional backtrace if `RUST_BACKTRACE=1` env is set):
`Compiler bug when jsifying ../../temp/tst.w:7:13 | panicked at 'Unexpected type: "Util" referenced inflight', libs/wingc/src/jsify.rs:1081:22`

This PR also adds two new features:
- Support for adding custom env variables to specific tests via the existing meta-comments mechanism:
```wing
/*\
env:
  MY_VAR: some value
\*/
log(util.env("MY_VAR"));
```
- A wing language "easter eggish" kind of feature for explicitly panicking the compiler via a new `😱` expression:
```wing
let x = 1;
😱; // This line will panic the compiler if `WINGC_DEBUG_PANIC=1` env is set.
```
possible values for `WINGC_DEBUG_PANIC` are `1` or `true` to make wingc panic as soon as it encounters `😱`, or you may explicitly specify the compilation phase in which you want the compiler to panic (`parsing`, `type checking`, `jsifying` see `set_compilation_context`).

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.